#! /usr/bin/python

CAMERA_HEIGHT = 2.654
CANE_HEIGHT = 1.03
BOX_SIZE_X = 0.3
BOX_SIZE_Y = 0.4
BOX_SIZE_Z = 0.93
BOX_SIZE_X_PADDED = BOX_SIZE_X*1.3
BOX_SIZE_Y_PADDED = BOX_SIZE_Y*1.3

CAMERA_TO_BOX_TOP = CAMERA_HEIGHT - BOX_SIZE_Z
CAMERA_TO_CANE_TOP = CAMERA_HEIGHT - CANE_HEIGHT